In [52]:
import pandas as pd
import numpy as np

In [53]:
start = 0
gap = 10000

In [54]:
DFList = []
for x in range(27):
    start = x*10000
    data = pd.read_csv('/Users/verafeng/Desktop/LCT_LancasterCountyTax/TaxSite_coordinate_'+ str(start)+ '-' + str(start+gap) +'.csv')
    DFList.append(data)
#     print(DFList[x].head())
# data = pd.read_csv('/Users/verafeng/Desktop/LCT_LancasterCountyTax/TaxSite_coordinate_'+ str(start)+ '-' + str(start+gap) +'.csv')

In [55]:
DFList[0].head()

,Unnamed: 0,ACCOUNTXREFNUM,ADDRESS1,ADDRESS2,CITY,STATE,POSTALCODE,COUNTRY,HOUSE_NUMBER,STREET_PREFIX,STREET,ZIPCODE,Owen_SCHOOL_DISTRICT,address,Unnamed: 14,coordinates
0,0,100000,124 PENNWICK DR,NaN,LITITZ,PA,17543-7623,NaN,124,NaN,PENNWICK DR,17543,NaN,"124 PENNWICK DR, LITITZ ,PA ,17543-7623",1,"[40.139776272920066, -76.29407994864162]"
1,1,100004,6 MEADOW VIEW DR,NaN,LEOLA,PA,17540-1650,NaN,6,NaN,MEADOW VIEW DR,17540,Conestoga Valley,"6 MEADOW VIEW DR, LEOLA ,PA ,17540-1650",2,"[40.09264548958398, -76.15864493355053]"
2,2,100005,52 W LINCOLN AVE,NaN,LITITZ,PA,17543-1034,NaN,52,W,LINCOLN AVE,17543,Warwick,"52 W LINCOLN AVE, LITITZ ,PA ,17543-1034",3,"[40.16070704244344, -76.31037212629114]"
3,3,100008,385 HOWARD AVE APT 8,NaN,LANCASTER,PA,17602-4237,NaN,385,NaN,HOWARD AVE,17602,Lancaster,"385 HOWARD AVE APT 8, LANCASTER ,PA ,17602-4237",4,"[40.0345788295942, -76.30222110495157]"
4,4,100011,111 MILLER RD APT C,NaN,AKRON,PA,17501-1178,NaN,111,NaN,MILLER RD,17501,Ephrata,"111 MILLER RD APT C, AKRON ,PA ,17501-1178",5,"[40.16451712320407, -76.20918326227714]"

In [63]:
#DFList[0], DFList[1]
output = DFList[0]
for x in range(26):
    x = x + 1
    frames = [output,DFList[x]]
    output = pd.concat(frames)

In [64]:
output

,Unnamed: 0,ACCOUNTXREFNUM,ADDRESS1,ADDRESS2,CITY,STATE,POSTALCODE,COUNTRY,HOUSE_NUMBER,STREET_PREFIX,STREET,ZIPCODE,Owen_SCHOOL_DISTRICT,address,Unnamed: 14,coordinates
0,0,100000,124 PENNWICK DR,NaN,LITITZ,PA,17543-7623,NaN,124,NaN,PENNWICK DR,17543,NaN,"124 PENNWICK DR, LITITZ ,PA ,17543-7623",1.0,"[40.139776272920066, -76.29407994864162]"
1,1,100004,6 MEADOW VIEW DR,NaN,LEOLA,PA,17540-1650,NaN,6,NaN,MEADOW VIEW DR,17540,Conestoga Valley,"6 MEADOW VIEW DR, LEOLA ,PA ,17540-1650",2.0,"[40.09264548958398, -76.15864493355053]"
2,2,100005,52 W LINCOLN AVE,NaN,LITITZ,PA,17543-1034,NaN,52,W,LINCOLN AVE,17543,Warwick,"52 W LINCOLN AVE, LITITZ ,PA ,17543-1034",3.0,"[40.16070704244344, -76.31037212629114]"
3,3,100008,385 HOWARD AVE APT 8,NaN,LANCASTER,PA,17602-4237,NaN,385,NaN,HOWARD AVE,17602,Lancaster,"385 HOWARD AVE APT 8, LANCASTER ,PA ,17602-4237",4.0,"[40.0345788295942, -76.30222110495157]"
4,4,100011,111 MILLER RD APT C,NaN,AKRON,PA,17501-1178,NaN,111,NaN,MILLER RD,17501,Ephrata,"111 MILLER RD APT C, AKRON ,PA ,17501-1178",5.0,"[40.16451712320407, -76.20918326227714]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12595,272595,774933,1429 PICKET DR,NaN,LANCASTER,PA,17601-4583,NaN,1429,NaN,PICKET DR,17601,Hempfield,"1429 PICKET DR, LANCASTER ,PA ,17601-4583",NaN,"[40.0694213516361, -76.36754717790984]"
12596,272596,774934,230 BEECH ST,NaN,DENVER,PA,17517-8609,NaN,230,NaN,BEECH ST,17517,Cocalico,"230 BEECH ST, DENVER ,PA ,17517-8609",NaN,"[40.232775082953644, -76.12889991704634]"
12597,272597,774935,61 W CHURCH ST,NaN,DENVER,PA,17517-9244,NaN,61,W,CHURCH ST,17517,Cocalico,"61 W CHURCH ST, DENVER ,PA ,17517-9244",NaN,"[40.22045882325084, -76.13024869821517]"
12598,272598,774936,840 COBBLESTONE LN,NaN,LANCASTER,PA,17601-3364,NaN,840,NaN,COBBLESTONE LN,17601,Manheim Township,"840 COBBLESTONE LN, LANCASTER ,PA ,17601-3364",NaN,"[40.09698914544972, -76.31321339676258]"
12599,272599,774937,205 GREENLAND DR,NaN,LANCASTER,PA,17602,NaN,205,NaN,GREENLAND DR,17602,Conestoga Valley,"205 GREENLAND DR, LANCASTER ,PA ,17602",NaN,"[40.02810684375889, -76.23212725243803]"

In [66]:
output.to_csv('/Users/verafeng/Desktop/LCT_LancasterCountyTax/Merged_with_none.csv')